### ISSUE TITLE
Injecting jQuery with Webpack breaks loading of dependant scripts in WP?

### ISSUE THREAD

**Issue by belamezey** [olefredrik/FoundationPress#1037]
Versions: WordPress 4.8.1 + FoundationPress 2.10.2

I've discovered that the latest FoundationPress deregisters the WordPress bundled jQuery and injects the newer version to app.js with Webpack. There seems to be a sideffect: WordPress thinks it has no jQuery and doesn't load other scripts that has jQuery dependency.

If I leave the bundled jQuery deregistered, but enqueue a later / the latest version from a CDN as FoundationPress did in earlier versions, than everything is working as expected.

**Comment by olefredrik** [comment]
@belamezey I would not enqueue jQuery from a CDN as we did in earlier versions, because then you would be loading jQuery twice (both from the CDN + injected with Webpack). 

I would think it's a better approach to load jQuery dependant scripts with webpack. Don't you think?

Here is a related thread: 
https://stackoverflow.com/questions/28969861/managing-jquery-plugin-dependency-in-webpack

**Comment by belamezey** [comment]
A deregistered jQuery means that webpack must load all jQuery dependant scripts from 3rd party WordPress plugins. At the moment I am still a complete webpack newbie, so I don't know yet if this is feasible.

For now I solved my problem with this approach:

- added jQuery as an external in gulpfile.babel.js -> webpackConfig so It's not bundled in
- loaded jQuery from CDN and added jquery as a dependency for the webpacked foundation js in enqueue-scripts.php

**Comment by olefredrik** [comment]
@belamezey : Hmm, that's clever 🤔  And you have no errors thrown in your console, right?

**Comment by belamezey** [comment]
@olefredrik : Yes, for me _npm start_ / _npm run build_ doesn't throw any error at the console. Also there are no javascript errors in the browser's console.

**Comment by olefredrik** [comment]
If that's the case, I think your solution is better than the one I've implemented in the current master branch. Want to make a pull request?

**Comment by nitrokevin** [comment]
Sorry to jump in here, but this is kind of related. I'm really struggling to get third party js working in the new foundation 6.4.1 now that is using webpacks - are there any simple instructions for doing this in foundationpress?

I'm trying to get scrollmagic working and have installed it with npm install scrollmagic --save but and lost with what you do next!

**Comment by belamezey** [comment]
> Want to make a pull request?

@olefredrik I've created a pull request for this issue.

**Comment by olefredrik** [comment]
Resolved in https://github.com/olefredrik/FoundationPress/pull/1040 

Kudos to @belamezey for fixing this

**Comment by JPOak** [comment]
I know plugins are not supported. However, I am wondering if anybody else has had any problems with some wordpress plugins conflicting with how FP is loading jquery. I'm getting "is not a function" errors. When I test the plugin on Twenty 15, 16, and 17 themes and no errors (plugins work fine). I am wondering if it is related to this thread.
